services:
  # --- JENKINS ---
  jenkins:
    #image: jenkins/jenkins:lts
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-local
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
      - ~/.kube:/root/.kube:ro
    environment:
      - GIT_SSL_NO_VERIFY=true
    restart: unless-stopped
    networks:
      - devops-network

  # --- POSTGRESQL ---
  postgres:
    image: postgres:17-alpine
    container_name: postgres-17-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - npm_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - devops-network

  # --- PGADMIN ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-local
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - ./pgadmin.json:/pgadmin4/pgadmin.json:ro
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - devops-network

  # --- PROMETHEUS ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-local
    ports:
      - "9090:9090"
    volumes:
      # [REVISI] Mengarahkan pembacaan file ke dalam folder config/
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - devops-network

  # --- GRAFANA ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-local
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - devops-network

volumes:
  jenkins_home:
  npm_pgdata:
  prometheus_data:
  grafana_data:

networks:
  devops-network:
    driver: bridge