FROM jenkins/jenkins
USER root

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# 1. Install Static Docker CLI
RUN curl -sSL -o docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-24.0.9.tgz && \
    tar -xzf docker.tgz && \
    mv docker/docker /usr/bin/docker && \
    chmod +x /usr/bin/docker && \
    rm -rf docker docker.tgz

# 2. Install Docker Buildx Plugin secara permanen
RUN mkdir -p /root/.docker/cli-plugins && \
    curl -sSL -o /root/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.14.0/buildx-v0.14.0.linux-amd64 && \
    chmod +x /root/.docker/cli-plugins/docker-buildx

# 3. Install Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# 4. Install ArgoCD CLI
# RUN curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && \
#     chmod +x /usr/local/bin/argocd

#USER jenkins