apiVersion: v1
kind: Namespace
metadata:
  name: artemis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  namespace: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
      - name: artemis
        image: apache/activemq-artemis:latest
        env:
        - name: ARTEMIS_USER
          value: admin
        - name: ARTEMIS_PASSWORD
          value: admin
        ports:
        - containerPort: 8161
        - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
  namespace: artemis
spec:
  type: LoadBalancer
  ports:
  - name: console
    port: 8161
    targetPort: 8161
  - name: broker
    port: 61616
    targetPort: 61616
  selector:
    app: artemis